03-02 19:32:00 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-02 19:32:00 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-02 19:32:34 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-02 19:32:34 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-02 19:33:40 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-02 19:33:40 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-02 19:33:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-02 19:33:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Schema "BDRE" already exists; SQL statement:
CREATE SCHEMA BDRE [90078-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateSchema.update(CreateSchema.java:46)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:180)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.onseven.dbvis.g.B.B.ā(Z:2603)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "BUS_DOMAIN" already exists; SQL statement:
CREATE TABLE  bus_domain  (
   bus_domain_id  integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
   description  varchar(256) NOT NULL,
   bus_domain_name  varchar(45) NOT NULL,
   bus_domain_owner  varchar(45) NOT NULL,
  PRIMARY KEY ( bus_domain_id )
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "BATCH_STATUS" already exists; SQL statement:
CREATE TABLE  batch_status  (
   batch_state_id  integer NOT NULL,
   description  varchar(45) NOT NULL,
  PRIMARY KEY ( batch_state_id )
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PROCESS_TYPE" already exists; SQL statement:
CREATE TABLE  process_type  (
   process_type_id  integer NOT NULL,
   process_type_name  varchar(45) NOT NULL,
   parent_process_type_id  integer,
  PRIMARY KEY ( process_type_id )
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EXEC_STATUS" already exists; SQL statement:
CREATE TABLE exec_status (
  exec_state_id integer NOT NULL,
  description varchar(45) NOT NULL,
  PRIMARY KEY (exec_state_id)
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "WORKFLOW_TYPE" already exists; SQL statement:
CREATE TABLE workflow_type (
  workflow_id integer NOT NULL,
    workflow_type_name varchar(45) NOT NULL,
    PRIMARY KEY (workflow_id)
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SERVERS" already exists; SQL statement:
CREATE TABLE  servers  (
   server_id  integer NOT NULL   GENERATED BY DEFAULT  AS IDENTITY (START WITH 1, INCREMENT BY 1),
   server_type  varchar(45) NOT NULL,
   server_name  varchar(45) NOT NULL,
   server_metainfo  varchar(45) DEFAULT NULL,
   login_user  varchar(45) DEFAULT NULL,
   login_password  varchar(45) DEFAULT NULL,
   ssh_private_key  varchar(512) DEFAULT NULL,
   server_ip  varchar(45) DEFAULT NULL,
  PRIMARY KEY ( server_id )
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PROCESS_TEMPLATE" already exists; SQL statement:
CREATE TABLE  process_template  (
   process_template_id  integer NOT NULL   GENERATED BY DEFAULT  AS IDENTITY (START WITH 1, INCREMENT BY 1),
   description  varchar(256) NOT NULL,
   add_ts  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   process_name  varchar(45) NOT NULL,
   bus_domain_id  integer NOT NULL,
   process_type_id  integer NOT NULL,
   parent_process_id  integer DEFAULT NULL,
   can_recover  BOOLEAN NOT NULL DEFAULT true ,
   batch_cut_pattern  varchar(45) DEFAULT NULL,
   next_process_template_id  VARCHAR(256) DEFAULT '' NOT NULL,
   delete_flag  BOOLEAN NOT NULL DEFAULT false,
   workflow_id  integer DEFAULT 1,
  PRIMARY KEY ( process_template_id ),
  CONSTRAINT  bus_domain_id_template  FOREIGN KEY ( bus_domain_id ) REFERENCES  bus_domain  ( bus_domain_id ) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT  original_process_id1_template  FOREIGN KEY ( parent_process_id ) REFERENCES  process_template  ( process_template_id ) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT  workflow_id_template  FOREIGN KEY ( workflow_id ) REFERENCES  workflow_type  ( workflow_id ) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT  process_type_id1_template  FOREIGN KEY ( process_type_id ) REFERENCES  process_type  ( process_type_id ) ON DELETE NO ACTION ON UPDATE NO ACTION

) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PROPERTIES_TEMPLATE" already exists; SQL statement:
CREATE TABLE properties_template (
  process_template_id integer NOT NULL,
  config_group varchar(128) NOT NULL,
  prop_temp_key varchar(128) NOT NULL,
  prop_temp_value varchar(2048) NOT NULL,
  description varchar(1028) NOT NULL,
  PRIMARY KEY (process_template_id,prop_temp_key),
  CONSTRAINT process_template_id5 FOREIGN KEY (process_template_id) REFERENCES process_template (process_template_id) ON DELETE NO ACTION ON UPDATE NO ACTION
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PROCESS" already exists; SQL statement:
CREATE TABLE process (
  process_id integer NOT NULL  GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  description varchar(256) NOT NULL,
  add_ts timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  process_name varchar(45) NOT NULL,
  bus_domain_id integer NOT NULL,
  process_type_id integer NOT NULL,
  parent_process_id integer DEFAULT NULL,
  can_recover boolean DEFAULT true,
   process_code VARCHAR(256),
  enqueuing_process_id integer NOT NULL DEFAULT 0,
  batch_cut_pattern varchar(45) DEFAULT NULL,
  next_process_id varchar(256) NOT NULL DEFAULT '',
  delete_flag boolean DEFAULT false,
  workflow_id integer DEFAULT 1,
  process_template_id integer DEFAULT 0,
  edit_ts TIMESTAMP AS NOW() NOT NULL,
  PRIMARY KEY (process_id),
  CONSTRAINT bus_domain_id FOREIGN KEY (bus_domain_id) REFERENCES bus_domain (bus_domain_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT original_process_id1 FOREIGN KEY (parent_process_id) REFERENCES process (process_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT process_ibfk_1 FOREIGN KEY (process_template_id) REFERENCES process_template (process_template_id),
  CONSTRAINT process_type_id1 FOREIGN KEY (process_type_id) REFERENCES process_type (process_type_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT workflow_id FOREIGN KEY (workflow_id) REFERENCES workflow_type (workflow_id) ON DELETE NO ACTION ON UPDATE NO ACTION
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PROPERTIES" already exists; SQL statement:
CREATE TABLE properties (
  process_id integer NOT NULL,
  config_group varchar(128) NOT NULL,
  prop_key varchar(128) NOT NULL,
  prop_value varchar(2048) NOT NULL,
  description varchar(1028) NOT NULL,
  PRIMARY KEY (process_id,prop_key),
  CONSTRAINT process_id4 FOREIGN KEY (process_id) REFERENCES process (process_id) ON DELETE NO ACTION ON UPDATE NO ACTION
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "INSTANCE_EXEC" already exists; SQL statement:
CREATE TABLE instance_exec (
  instance_exec_id bigint NOT NULL  GENERATED BY DEFAULT  AS IDENTITY (START WITH 1, INCREMENT BY 1),
  process_id int NOT NULL,
  start_ts timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_ts timestamp  DEFAULT NULL,
  exec_state int NOT NULL,
  PRIMARY KEY (instance_exec_id),
  CONSTRAINT process_id_instance_exec FOREIGN KEY (process_id) REFERENCES process (process_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT exec_state_instance_exec FOREIGN KEY (exec_state) REFERENCES exec_status (exec_state_id) ON DELETE NO ACTION ON UPDATE NO ACTION
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "BATCH" already exists; SQL statement:
CREATE TABLE batch (
  batch_id bigint NOT NULL  GENERATED BY DEFAULT  AS IDENTITY (START WITH 1, INCREMENT BY 1),
  source_instance_exec_id bigint DEFAULT NULL,
  batch_type varchar(45) NOT NULL,
  PRIMARY KEY (batch_id),
  CONSTRAINT instance_exec_id FOREIGN KEY (source_instance_exec_id) REFERENCES instance_exec (instance_exec_id) ON DELETE NO ACTION ON UPDATE NO ACTION
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "FILE" already exists; SQL statement:
CREATE TABLE file (
  batch_id bigint NOT NULL,
  server_id int NOT NULL,
  path varchar(256) NOT NULL,
  file_size bigint NOT NULL,
  file_hash varchar(100) DEFAULT NULL,
  creation_ts TIMESTAMP AS NOW() NOT NULL,
  CONSTRAINT server_id FOREIGN KEY (server_id) REFERENCES servers (server_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT unique_batch FOREIGN KEY (batch_id) REFERENCES batch (batch_id) ON DELETE NO ACTION ON UPDATE NO ACTION
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "BATCH_CONSUMP_QUEUE" already exists; SQL statement:
CREATE TABLE batch_consump_queue (
  source_batch_id bigint NOT NULL,
  target_batch_id bigint DEFAULT NULL,
  queue_id bigint NOT NULL  GENERATED BY DEFAULT  AS IDENTITY (START WITH 1, INCREMENT BY 1),
  insert_ts TIMESTAMP AS NOW() NOT NULL,
  source_process_id int DEFAULT NULL,
  start_ts timestamp  DEFAULT NULL,
  end_ts timestamp  DEFAULT NULL,
  batch_state int NOT NULL,
  batch_marking varchar(45) DEFAULT NULL,
  process_id int NOT NULL,
  PRIMARY KEY (queue_id),
  CONSTRAINT batch_state_bcq FOREIGN KEY (batch_state) REFERENCES batch_status (batch_state_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT process_id_bcq FOREIGN KEY (process_id) REFERENCES process (process_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT source_batch_bcq FOREIGN KEY (source_batch_id) REFERENCES batch (batch_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT target_batch_bcq FOREIGN KEY (target_batch_id) REFERENCES batch (batch_id) ON DELETE NO ACTION ON UPDATE NO ACTION
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ARCHIVE_CONSUMP_QUEUE" already exists; SQL statement:
CREATE TABLE archive_consump_queue (
  source_batch_id bigint NOT NULL,
  target_batch_id bigint DEFAULT NULL,
  queue_id bigint NOT NULL  GENERATED BY DEFAULT  AS IDENTITY (START WITH 1, INCREMENT BY 1),
  insert_ts TIMESTAMP AS NOW() NOT NULL,
  source_process_id int DEFAULT NULL,
  start_ts timestamp  DEFAULT NULL,
  end_ts timestamp  DEFAULT NULL,
  batch_state int NOT NULL,
  batch_marking varchar(45) DEFAULT NULL,
  process_id int NOT NULL,
  PRIMARY KEY (queue_id),
  CONSTRAINT process_id_archive_consump_queue FOREIGN KEY (process_id) REFERENCES process (process_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT batch_state_archive_consump_queue FOREIGN KEY (batch_state) REFERENCES batch_status (batch_state_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT source_batch_archive_consump_queue FOREIGN KEY (source_batch_id) REFERENCES batch (batch_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT target_batch_archive_consump_queue FOREIGN KEY (target_batch_id) REFERENCES batch (batch_id) ON DELETE NO ACTION ON UPDATE NO ACTION

) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" already exists; SQL statement:
CREATE  TABLE users (
  username VARCHAR(45) NOT NULL ,
  password VARCHAR(45) NOT NULL ,
  enabled boolean DEFAULT true ,
  PRIMARY KEY (username)) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USER_ROLES" already exists; SQL statement:
CREATE TABLE user_roles (
  user_role_id INT NOT NULL  GENERATED BY DEFAULT  AS IDENTITY (START WITH 1, INCREMENT BY 1),
  username VARCHAR(45) NOT NULL,
  ROLE VARCHAR(45) NOT NULL,
  PRIMARY KEY (user_role_id),
  CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username)) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PROCESS_LOG" already exists; SQL statement:
CREATE TABLE  process_log  (
   log_id  bigint NOT NULL  GENERATED BY DEFAULT  AS IDENTITY (START WITH 1, INCREMENT BY 1),
   add_ts  timestamp,
   process_id  int NOT NULL,
   log_category  varchar(10) NOT NULL,
   message_id  varchar(128) NOT NULL,
   message  varchar(1024) NOT NULL,
   instance_ref  bigint,
  PRIMARY KEY ( log_id ),
  CONSTRAINT  process_id  FOREIGN KEY ( process_id ) REFERENCES  process  ( process_id ) ON DELETE NO ACTION ON UPDATE NO ACTION
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "INTERMEDIATE" already exists; SQL statement:
CREATE TABLE  intermediate  (
   uuid  varchar(64) NOT NULL,
   inter_key  varchar(128) NOT NULL,
   inter_value  varchar(2048) NOT NULL,
  PRIMARY KEY ( inter_key , uuid )
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LINEAGE_NODE_TYPE" already exists; SQL statement:
CREATE TABLE  lineage_node_type  (
   node_type_id  int NOT NULL,
   node_type_name  varchar(45) NOT NULL,
  PRIMARY KEY ( node_type_id )
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LINEAGE_QUERY_TYPE" already exists; SQL statement:
CREATE TABLE  lineage_query_type  (
   query_type_id  INT NOT NULL,
   query_type_name  varchar(255) NOT NULL,
  PRIMARY KEY ( query_type_id )
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LINEAGE_QUERY" already exists; SQL statement:
CREATE TABLE  lineage_query  (
   query_id  varchar(100) NOT NULL,
   query_string  varchar(4000) ,
   query_type_id  int NOT NULL,
   create_ts  timestamp DEFAULT CURRENT_TIMESTAMP,
   process_id  int,
   instance_exec_id  bigint DEFAULT NULL,
  PRIMARY KEY ( query_id ),
  CONSTRAINT  query_type_id  FOREIGN KEY ( query_type_id ) REFERENCES  lineage_query_type  ( query_type_id ) ON DELETE NO ACTION ON UPDATE NO ACTION
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LINEAGE_NODE" already exists; SQL statement:
CREATE TABLE  lineage_node  (
   node_id  varchar(100) NOT NULL,
   node_type_id  int NOT NULL,
   container_node_id  varchar(100) DEFAULT NULL,
   node_order  int DEFAULT 0,
   insert_ts  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   update_ts  timestamp  DEFAULT NULL,
   dot_string  varchar(4000),
   dot_label  varchar(4000),
   display_name  varchar(256) DEFAULT NULL,
  PRIMARY KEY ( node_id ),
  CONSTRAINT  conatiner_node_id  FOREIGN KEY ( container_node_id ) REFERENCES  lineage_node  ( node_id ) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT  node_type  FOREIGN KEY ( node_type_id ) REFERENCES  lineage_node_type  ( node_type_id ) ON DELETE NO ACTION ON UPDATE NO ACTION
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "LINEAGE_RELATION" already exists; SQL statement:
CREATE TABLE  lineage_relation  (
   relation_id  varchar(100) NOT NULL,
   src_node_id  varchar(100) DEFAULT NULL,
   target_node_id  varchar(100) DEFAULT NULL,
   query_id  varchar(100) NOT NULL,
   dot_string  varchar(4000),
  PRIMARY KEY ( relation_id ),
  CONSTRAINT  src_node_id  FOREIGN KEY ( src_node_id ) REFERENCES  lineage_node  ( node_id ) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT  target_node_id  FOREIGN KEY ( target_node_id ) REFERENCES  lineage_node  ( node_id ) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT  query_id  FOREIGN KEY ( query_id ) REFERENCES  lineage_query  ( query_id ) ON DELETE NO ACTION ON UPDATE NO ACTION
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPLOY_STATUS" already exists; SQL statement:
CREATE TABLE deploy_status (
  deploy_status_id smallint NOT NULL,
  description varchar(45) NOT NULL,
  PRIMARY KEY (deploy_status_id)
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERAL_CONFIG" already exists; SQL statement:
CREATE TABLE general_config (
   config_group varchar(128) NOT NULL,
  gc_key varchar(128) NOT NULL,
  gc_value varchar(2048) ,
  description varchar(1028) NOT NULL,
  required boolean DEFAULT false NOT NULL,
  default_val varchar(2048)  ,
  type varchar(20)  DEFAULT 'text' NOT NULL,
  enabled boolean DEFAULT true,
  PRIMARY KEY (config_group,gc_key)
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PROCESS_DEPLOYMENT_QUEUE" already exists; SQL statement:
CREATE TABLE  process_deployment_queue  (
    deployment_id  bigint NOT NULL  GENERATED BY DEFAULT  AS IDENTITY (START WITH 1, INCREMENT BY 1),
    process_id  int NOT NULL ,
    start_ts  timestamp  DEFAULT NULL,
    insert_ts  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_ts  timestamp DEFAULT NULL,
    deploy_status_id  smallint NOT NULL DEFAULT 1,
    user_name  varchar(45) NOT NULL,
    bus_domain_id  int NOT NULL,
    process_type_id  int NOT NULL,
    deploy_script_location  varchar(1000) DEFAULT NULL,
  PRIMARY KEY ( deployment_id ),
  CONSTRAINT  deploy_status_id  FOREIGN KEY ( deploy_status_id ) REFERENCES  deploy_status  ( deploy_status_id ) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT  deploy_process_id  FOREIGN KEY ( process_id ) REFERENCES  process  ( process_id ) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT  deploy_process_type_id  FOREIGN KEY ( process_type_id ) REFERENCES  process_type  ( process_type_id ) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT  deploy_bus_domain_id  FOREIGN KEY ( bus_domain_id ) REFERENCES  bus_domain  ( bus_domain_id ) ON DELETE NO ACTION ON UPDATE NO ACTION
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DOCIDSDB" already exists; SQL statement:
CREATE TABLE Docidsdb (
   docid bigint NOT NULL  GENERATED BY DEFAULT  AS IDENTITY (START WITH 1, INCREMENT BY 1) ,
   url varchar(3000),
   PRIMARY KEY (docid)
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "STATISTICSDB" already exists; SQL statement:
CREATE TABLE Statisticsdb (
   uniqid bigint NOT NULL  GENERATED BY DEFAULT  AS IDENTITY (START WITH 1, INCREMENT BY 1),
   value bigint,
   name varchar(255),
   PRIMARY KEY (uniqid)
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PENDINGURLSDB" already exists; SQL statement:
CREATE TABLE Pendingurlsdb (
   uniqid bigint NOT NULL  GENERATED BY DEFAULT  AS IDENTITY (START WITH 1, INCREMENT BY 1),
   pid bigint,
   instanceexecid bigint,
   url varchar(3000),
   docid int not null,
   parentdocid int not null,
   parenturl varchar(1000),
   depth smallint not null,
   domain varchar(255),
   subdomain varchar(255),
   path varchar(1000),
   anchor varchar(255),
   priority int not null,
   tag varchar(255),
   PRIMARY KEY (uniqid)
) [42101-172]
03-02 19:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "WEBURLSDB" already exists; SQL statement:
CREATE TABLE Weburlsdb (
   uniqid bigint NOT NULL  GENERATED BY DEFAULT  AS IDENTITY (START WITH 1, INCREMENT BY 1),
   pid bigint,
   instanceexecid bigint,
   url varchar(3000),
   docid int not null,
   parentdocid int not null,
   parenturl varchar(1000),
   depth smallint not null,
   domain varchar(255),
   subdomain varchar(255),
   path varchar(1000),
   anchor varchar(255),
   priority int not null,
   tag varchar(255),
   PRIMARY KEY (uniqid)
) [42101-172]
03-02 19:44:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-02 19:44:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-02 19:44:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-02 19:44:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-03 15:52:55 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-03 15:52:55 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-11 14:37:13 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-11 14:37:13 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-11 14:37:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
03-11 14:37:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
